version: 2.1

jobs:
  build-web:
    machine: true
    working_directory: /web
    steps:
      - checkout
      - run: docker login registry.digitalocian.com --username $DO_API_KEY --password $DO_API_KEY
      - run: docker build -t git_flow_test/web:$CIRCLE_BRANCH
      - run: docker push git_flow_test/web:$CIRCLE_BRANCH
    

  build-db:
    machine: true
    working_directory: /db
    steps:
      - checkout
      - run: docker login registry.digitalocian.com --username $DO_API_KEY --password $DO_API_KEY
      - run: docker build -t git_flow_test/web:$CIRCLE_BRANCH
      - run: docker push git_flow_test/web:$CIRCLE_BRANCH
  tag-branch:
    machine: true
    worcking_directory:
    steps:
      - checkout
      - run:
          shell: /bin/sh
          command: | 
            latestTag=$(git describe --tags --abbrev=0)
            lastOctet=$(echo $latestTag | awk -F '.' '{print $3}')
            newTag=$(echo "${latestTag/%.$lastOctet/.$(($lastOctet+1))}")
            git tag -a $newTag -m "commit tagged by circleCI"
            git push origin --tags

workflows:
  build-and-tag:
    jobs:
      - build-db
      - build-web
      - increment-tag
    triggers:
      filters:
        branches:
          only:
             - develop  

